services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatealas-laravel
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: gatealas_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      CACHE_STORE: file
      APP_ENV: local
      MS_DONACIONES_URL: http://donaciones.dasalas.shop
      MS_LOGISTICA_URL: http://das.dasalas.shop
      MS_BRIGADAS_URL: http://brigadas.dasalas.shop
      MS_VOLUNTARIOS_POST_URL: http://gevopi.dasalas.shop
      MS_ANIMALES_URL: http://rescate.dasalas.shop
      MS_PREDICCION_URL: http://sipi.dasalas.shop
    depends_on:
      - db
    networks:
      - gatealas-net
  nginx:
    image: nginx:latest
    container_name: gatealas
    expose:
      - "80"
    # ports:
    #   - "8080:80" ---> despliegue local con puerto 8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - gatealas-net
      - internal-network
      - proxy-network
  db:
    image: postgres:latest
    container_name: gatealas-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gatealas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - gatealas-net

networks:
  gatealas-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true

volumes:
  db-data: